env: "HalfCheetah-v3"
default_config: "configs/default.yaml"
max_timesteps: 1000
population_size: 100
planning_horizon: 2
beta: 0.25
sigma_init: 0.2
reward_module: "reward_functions/halfcheetah.py"
pessimism_coef: 50
penalty: 30
alg: "alg_mbop"