env: "Hopper-v2"
default_config: "configs/default.yaml"
max_timesteps: 1000
population_size: 500
n_iterations: 5
elite_size: 50
planning_horizon: 100
beta: 2
reward_module: "reward_functions/hopper.py"
pessimism_coef: 20
penalty: 50