env: "maze2d-umaze-v1"
default_config: "configs/default.yaml"
max_timesteps: 300
population_size: 1000
n_iterations: 5
planning_horizon: 50
beta: 2.0
reward_module: "reward_functions/maze2d.py"
model: "models/d4rl_maze2d_umaze_v1_scheduler_123.pickle"
dataset: "datasets/d4rl_maze2d_umaze_v1.pickle"
pessimism_coef: 50
penalty: 10